layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    forks: true
    projects:
      # - gotql
      # - delay.css
      # - my-notes
      # - design-patterns-for-humans
      # - nxcd/tardis
      # - nxcd/paradox

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: lhs-santos
  mvp: 5003259
  stackoverflow: 17502
  twitter: _staticvoid
  telegram: lhs_santoss
  medium: khaosdoctor
  speakerdeck: khaosdoctor
  telegram: lhs_santoss
  # youtube: your_username

topics:
  - name: NodeJS
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/fd96fceccf8c42c99cbe29cf0f8dcc4736fcb85a/topics/nodejs/nodejs.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/typescript/typescript.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/docker/docker.png

  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/kubernetes/kubernetes.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/python/python.png

  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/go/go.png

  - name: Vue
    web_url: https://github.com/topics/vue
    image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/vue/vue.png

  - name: React
    web_url: https://github.com/topics/react
    image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/react/react.png

  - name: Terraform
    web_url: https://github.com/topics/terraform
    image_url: https://raw.githubusercontent.com/github/explore/a78365e1ed698ba6441a91508591e863cf1f9590/topics/terraform/terraform.png

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/css/css.png

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/sass/sass.png
